name: cdnbye_ijk_example
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ijkplayer: ^0.3.5+1
  # iOS的按钮效果
  tapped: ^1.0.2
  # map安全取值
  safemap: ^1.1.0
  # 本地缓存
  local_cache_sync: ^1.1.0
  # 左滑删除
  left_scroll_actions: ^1.5.2
  # 读取写入文件
  path_provider: ^1.4.5
  # dio: ^3.0.5
  # 下拉刷新
  # pull_to_refresh: ^1.5.7
  # 由于网络原因，cdnbye的最新版可能并不能及时上传pub，若要使用最新版，请使用github版本
  cdnbye: ^0.8.1
  # cdnbye:
  # path: /Users/majialun/Desktop/code/P2P-Engine/flutter-p2p-engine
  #   git:
  #     url: https://github.com/cdnbye/flutter-p2p-engine.git
  #     ref: master
  # 弹窗库
  # oktoast: ^2.2.1
  # 载入动画
  # flutter_spinkit: "^3.0.0"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # assets-generator-begin
    # assets/*
    - assets/example.png
    - assets/logo.png
    # assets-generator-end
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
